name: ZAP DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: ZAP API Scan
    uses: zaproxy/action-api-scan@v0.9.0