name: ZAP DAST Scan

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  zap_scan:
    runs-on: ubuntu-latest
    needs: security
    name: Run DAST scan on the web applications
    steps:
      - name: Checkout repo (opcional)
        uses: actions/checkout@v3

      - name: Start your app
        run: |
          # Asegúrate de que tu app se pueda levantar así
          npm install
          npm run build || true
          npm start &
          sleep 10  # Espera a que tu app esté corriendo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://testphp.vulnweb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'