name: ZAP DAST Scan

on:
  workflow_dispatch:  # Se ejecuta manualmente desde GitHub UI

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Run ZAP DAST scan

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build app
        run: |
          npm install
          npm run build || true

      - name: Start the application
        run: |
          npm start &
          sleep 15  # Esperar a que la app esté completamente arriba

      - name: Run ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.6.1
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'http://localhost:3000'  # Tu app corriendo localmente
          cmd_options: '-a'                # Escaneo activo (puede tardar más)

      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-dast-report
          path: report_html.html
